SELECT 

--E2_CODAPRO,E2_USUALIB,E2_DATALIB,E2_STATLIB,SE2.*,FRP.*,USR.* 
SM0.M0_CODIGO,SM0.M0_CODFIL,SM0.M0_NOMECOM,
SE2.E2_PREFIXO,SE2.E2_NUM,SE2.E2_PARCELA,
SA2.A2_COD,SA2.A2_LOJA,SA2.A2_NREDUZ,
SED.ED_CODIGO,SED.ED_DESCRIC,
--CENTRO DE CUSTO DE APROVAO SE2.E2_XCCAPRV
SE2.E2_VENCREA,SE2.E2_VLCRUZ,SE2.E2_TIPO,SX5.X5_DESCRI,
USR.USR_NOME,USR.USR_EMAIL,USR.USR_CODIGO

FROM SE2990 SE2

INNER JOIN SX5990 SX5 
ON SE2.E2_TIPO = SX5.X5_CHAVE

INNER JOIN SA2990 SA2 
ON SE2.E2_FORNECE = SA2.A2_COD 
AND SE2.E2_LOJA = SA2.A2_LOJA

INNER JOIN SYS_COMPANY SM0 
ON SE2.E2_FILIAL = SM0.M0_CODFIL

INNER JOIN SED990 SED 
ON SE2.E2_FILIAL = SED.ED_FILIAL 
AND SE2.E2_NATUREZ = SED.ED_CODIGO 
AND SE2.D_E_L_E_T_ = SED.D_E_L_E_T_ 

INNER JOIN FRP990 FRP 
ON SE2.E2_CODAPRO = FRP.FRP_COD 
AND SE2.D_E_L_E_T_ = FRP.D_E_L_E_T_

INNER JOIN SYS_USR USR 
ON FRP.FRP_USER = USR.USR_ID 
AND FRP.D_E_L_E_T_ = USR.D_E_L_E_T_

WHERE SE2.D_E_L_E_T_ = ' ' 
AND SM0.M0_CODIGO = '99' 
AND SX5.X5_TABELA = '05'
AND SE2.E2_XWFSEND = 'F'


